### PR TITLE
trackdb: Insist on creating new DBs using bsddb, not any other dbm backend

### PR DESCRIPTION
**Pull request by sjohannes**
I think the gdbm module in MSYS2 is [broken](https://github.com/exaile/exaile/issues/386), so this completely sidesteps it.

On other platforms bsddb also has advantages. [The only benchmark I can find](http://tokyocabinet.sourceforge.net/benchmark.pdf) says Berkeley DB is marginally better than GDBM. ~~It's also more likely to already be installed (only talking about the library, not the Python module), according to a quick reverse dependency search on Debian and Arch~~ (**update:** this is wrong; lots of things require gdbm as well).

If the user really really wants to use gdbm or any of the other dbm backends, they can create their own music.db with that backend; when the bsddb part of this patch fails, it falls back to using `shelve.open`.

### CODE REVIEW

**Comment by sjohannes** [comment]
Note that if your music.db is already created broken (empty file), you need to delete it first.

**Comment by virtuald** [comment]
Hm. The way I was thinking about this, it would try to automatically upgrade you to bsddb3 if it detected a different type.

Also, the lyrics cache needs to be updated also. I was thinking maybe we move this to a utility class?

**Comment by genodeftest** [comment]
> Hm. The way I was thinking about this, it would try to automatically upgrade you to bsddb3 if it detected a different type.

+1, preferably with a new name to make database type detection easier. (migration).

Still, the current solution in 6cfd5fe fixes the core issue. The migration code can be added later.

**Comment by virtuald** [comment]
I'm going to steal this code and move it into xl.common, and open a new PR in a few minutes.

**Pull request closed without merging**
