### PR TITLE
Replace cddb by libdiscid

### PR DESCRIPTION
**Pull request by ryneeverett**
This just a rebase and python syntax and formatting update of #652.

### CODE REVIEW

**Comment by luzip665** [comment]
I tested with a couple of cds. Fetching the track information seems to work for me.

But there are some problems in the plugin preferences that prevent importing a cd. Can you fix them in this branch?

**Review by luzip665 — CHANGES_REQUESTED** [review]

**Comment by rokm** [comment]
> @sjohannes The package discid should be added to `tools/installer/requirements.txt`, right? What about its dependency to libdiscid (https://python-discid.readthedocs.io/en/latest/install/#libdiscid) ?

`discid` goes to `tools/installer/requirements.txt`, and `mingw-w64-i686-libdiscid` goes [here](https://github.com/exaile/python-gtk3-gst-sdk/blob/master/win_installer/data/sdk.config). We'll need a PyInstaller hook for `discid` to collect that shared lib (I'll probably add one upstream, so by the time this is sorted out and merged it will work out of the box).

**Comment by luzip665** [comment]
Thank you for fixing!
I'll check at weekend

**Review by luzip665 — COMMENTED** [review]
Works for me.
Please, can you rebase? Then I will merge.

**Comment by luzip665** [comment]
Thanks for rebasing.
But I mean it a way that results in one commit with a well readable commit message.

@rokm It's not working on windows because of missing dbus, right?

**Comment by rokm** [comment]
> @rokm It's not working on windows because of missing dbus, right?

Yeah, looks like the `cd` plugin requires udisks2 (accessible via dbus) for listing devices. 

Which makes my earlier comment about installing `discid` on Windows moot, since the plugin does not work on that platform in the first place...

**Pull request merged**
