### PR TITLE
Get rid of a few warnings

### PR DESCRIPTION
**Pull request by genodeftest**

### CODE REVIEW

**Comment by virtuald** [comment]
What warnings are you trying to get rid of?

**Comment by genodeftest** [comment]
Just a few codestyle warnings by pydev, pylint and pep8.

**Comment by genodeftest** [comment]
Why? Is there anything wrong with what I'm doing?

**Comment by virtuald** [comment]
Nope, just was wondering which warnings, since the changes seemed small. :)

**Pull request merged**
