### PR TITLE
splash.ui: Splash screen is no popup window

### LINKED ISSUE #342: Splash screen isn't showing on OSX/Fedora 25
GTK 3.22. On Linux there's a warning (see below). No warning on OSX, but no splash screen either.

```
Gdk-Message: Window 0x560cc8b08320 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: Window 0x560cc8b08320 is a temporary window without parent, application will not be able to position it on screen.
```

### PR DESCRIPTION
**Pull request by genodeftest**
This change should fix #342 or at least get around the warnings.

@virtuald : Can you please test under OS X, if this fixes #342?

### CODE REVIEW

**Comment by genodeftest** [comment]
Sorry, I messed this up and will retry.

**Comment by virtuald** [comment]
You can just force push to the same branch.

**Comment by genodeftest** [comment]
I could, but I cannot modify any branch I created under the "exaile" Github organization. See #349 for a new try.

**Comment by virtuald** [comment]
Heh, that shouldn't be the case.

**Pull request closed without merging**
