### PR TITLE
Fixes for Makefile

### PR DESCRIPTION
**Pull request by sarnold**
for amazoncovers plugin to work.  I forgot about this one, and I promise to start testing gi branch now...  really...

### CODE REVIEW

**Comment by virtuald** [comment]
Unless I'm reading it incorrectly, nothing in that file uses lxml, why does the import need to happen there?

**Comment by sarnold** [comment]
AFAICT amazon cover lookup is broken without it; the imports are a little bit different between 0.3x and 3.x/HEAD but it pretty much needs to go somewhere (_ecs maybe?).  It also needs valid AWS credentials, but Amazon lookup works in both old and new with the patch.

**Comment by sarnold** [comment]
Top commit fixes issue #70 (see commit msg for interesting details).

**Comment by sarnold** [comment]
It probably went in early in debugging the missing "/usr" path, but in this case it should be safer than not (or relying on upstream packagers like me to add MAKEOPTS=-j1 as a workaround).  Otherwise your two different make targets have a potential race condition between creating the target dirs and installing to the same dirs (and in this case you lose nothing since you're not really compiling anything that's worth doing in parallel in the first place, plus it's not worth the maintenance headache for a static makefile; better to switch to autotools at that point).

**Comment by sarnold** [comment]
Oh, and the rest of the makefile updates are to make it more consistent and flexible for OS/package maintainers (as well as developers) as it fixes an inconsistency in how EPREFIX and EXAILE* dirs were being used.  The makefile cleanup ended up getting a /usr/usr/blah path in the launcher script, as it changes the args to be more self-consistent/correct.  Did I mention static makefiles were a maintenance headache?  Autotools *does* do python, or distutils/setuptools are another option.

**Comment by sjohannes** [comment]
I've moved my #70-related comments there; I didn't expect them to appear in this PR.

**Comment by sarnold** [comment]
Turns out it does work in the latest version (without the import).  Thought I tested it in that version, but apparently I just migrated the patch.

**Comment by virtuald** [comment]
@sarnold if you could rebase this down to a single commit, that would be great and we can merge it in to master (unless @sjohannes has additional objections).

**Comment by sarnold** [comment]
Check.

**Comment by virtuald** [comment]
Thanks!

**Pull request merged**
