### PR TITLE
reduce size of description, reduce UI elements (again)

### PR DESCRIPTION
**Pull request by genodeftest**
I accidentially closed #106, this is the change from there.

### CODE REVIEW

**Comment by virtuald** [comment]
This behavior seems fine to me, with the exception that having the two checkboxes move over and over again is a bit annoying. 

I wonder if we should move them to somewhere they won't move (maybe top or bottom). I feel like we're [bikeshedding](http://bikeshed.com/) this a bit too much though...

**Comment by virtuald** [comment]
@sjohannes ?

**Comment by genodeftest** [comment]
You're right. I second moving them up or down. Any preference?

**Comment by sjohannes** [comment]
No preference between top, middle, and bottom for me.

**Comment by virtuald** [comment]
Thanks!

**Pull request merged**
