### PR TITLE
Makefile: Move to build dir, remove unnecessary script

### LINKED ISSUE #418: Makefile: put generated files in separate directory
### Steps to Reproduce (for bugs)
1. run `make all` or some other `make` targets
2. have a look at the generated files

### Expected Behavior
All generated files should be in a subfolder, e.g. "build/" or the "dist/" folder created by `make dist`

### Current Behavior
Generated files (man page, bash completion, locale) are written in-place, cluttering the source folder.

### Environment
* Operating System and version: Any
* Exaile Version: Exaile 4.0.0 beta 2 or git master

### LINKED ISSUE #419: Makefiles: Improve error messages about locales
### Steps to Reproduce (for bugs)
1. run `make locale`

### Expected Behavior
For every warning, it should be clear which file causes it.

### Current Behavior
No notion of any filename. How should I determine which file causes the warning or error?

### Environment
* Exaile Version: Exaile 4.0.0 beta 2

### PR DESCRIPTION
**Pull request by genodeftest**
* remove po/Makefile and tools/compilepo.sh, move those statements into main Makefile.
* move built translations, bash-completion file and man page to builddir
* update clean target to reflect changes

Fixes #418, fixes #419

### CODE REVIEW

**Comment by genodeftest** [comment]
I am not 100% sure this does not break the Windows installer. Can someone please check that?

**Comment by virtuald** [comment]
Why a build directory?

**Comment by genodeftest** [comment]
> Why a build directory?

To not have binary/compiled/generated files clutter the source/locale directories.

**Comment by genodeftest** [comment]
> Why a build directory?

To not have binary/compiled/generated files clutter the source/locale directories. Same stuff you do already in the `doc/` subfolder.

**Comment by virtuald** [comment]
If it breaks the Windows installer, we can fix it later. I don't think it will though, as the windows installer uses a `make install` to install into a custom prefix, so if you broke that then everything's broken...

**Pull request merged**
