### PR TITLE
Don't write empty log files

### PR DESCRIPTION
**Pull request by luzip665**
see #769

### CODE REVIEW

**Review by genodeftest — APPROVED** [review]
Looks good to me. Thank you!

**Comment by genodeftest** [comment]
@luzip665 : Hint: There are codewords in Github on pull requests ([documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). If you add them to the text (description) of the pull request, you can make the linked issue automatically get closed if PRs like this get merged. Example for this PR's description:
```
fixes #769
```

**Comment by sjohannes** [comment]
I usually use the full URL like this:

    Fixes: https://github.com/exaile/exaile/pull/769

and put it in the commit message. This makes it available in the Git log and makes it easier to click / copy from outside the GitHub UI. GitHub also detects this and closes the linked ticket.

**Comment by genodeftest** [comment]
That's even better, thank you!

**Comment by luzip665** [comment]
@sjohannes Thank you for the hint!

**Pull request merged**
