### PR TITLE
Covers: Support multiple albums having the same name

### PR DESCRIPTION
**Pull request by sjohannes**
See #306 for the motivation for this patch.

One of the exciting changes here is that it adds support for the `musicbrainz_albumid` tag. When this tag is available, we don't need to check anything else; it uniquely identifies the album.

This patch also incorporates @sbrubes's idea to use the `date` tag, because [one artist can release multiple albums with the same name](https://forums.macrumors.com/threads/itunes-two-albums-with-same-name-and-album-artist.1505017/).

So the possible track keys are, in order of preference (`[]` means the tag will be used iff it's available):

* musicbrainz_albumid
* album albumartist [date]
* __compilation [date]  # __compilation is a (directory, album) tuple
* album [artist] [date]

I've also changed the format of the output of this function. The function can return anything we like as long as it's hashable. Currently we return a tuple containing another tuple containing strings. My patch changes this to just a unicode string separated by null characters, e.g. `u'tag1\0value1\0tag2\0value2'`. It should make the dict lookup (hashing) marginally faster.

Here's what the new covers.db looks like, unpickled:

    {
        u"__compilation\x00/my/dir\x01my album\x00date\x002000":
            'localfile:file:///my/dir/cover.jpg',
        u'album\x00My Album\x00albumartist\x00My Albumartist\x00date\x002000':
            'tags:cover:0:file:///my/dir/file.mp3',
        u'musicbrainz_albumid\x00aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee':
            'localfile:file:///my/dir/cover.png',
    }

Any thoughts on all this?

Open questions regarding the migration:

1. What should we do with the existing cache? We could leave it as is, but that means having the existing entries (which are all stale) take up useless space. I vote [trashing](https://developer.gnome.org/gio/stable/GFile.html#g-file-trash) `$cachedir/covers`.
2. Should we reuse the directory/file name or use a new one, e.g. `$cachedir/covers2`, in case the user wants to use it in parallel with Exaile 3?
3. Do we do the migration in `covers.py` itself, or should we use a global 3→4 migration mechanism?

### CODE REVIEW

**Comment by sbrubes** [comment]
The easier solution it's using the same directory and emptying it on Exaile's 4 first run.
It will have the cost of extra space when you run Exaile 3 and 4, but who wanna do that, could be aware about it.

I don't see how a migration 3->4 could be done, unless you do it progressive (as covers are requested).
But it should keep the old code, what it's quite unnecessary.

**Comment by sbrubes** [comment]
As we are discussing that, maybe the issue #10, could be considered to be fixed. 

Using the dirname as db_key, when no album tag it’s found?

**Comment by sjohannes** [comment]
I don't fully understand #10, but I think it's possible to do now with musicbrainz_albumid. It needs manual tagging but it's very precise and doesn't need Exaile to guess things.

**Comment by sjohannes** [comment]
In the latest push I've added the migration code.

It's pretty tricky because there's not enough info in the old covers.db to create the new one. So the best I can do is migrate just the covers from tracks that exist in the user's Collection. Covers from non-Collection tracks are not migrated, and the image files associated with these tracks are also deleted from the cache.

**Pull request merged**
