### PR TITLE
BREAK ALL THE THINGS

### PR DESCRIPTION
**Pull request by virtuald**
I'm not 100% convinced this is a good idea, but here it is anyways. The UI *starts* at least for me... I got this by running pygi-convert.sh and then fixing things manually until it worked.

Probably a better way of going about this is doing it a single file at a time instead of wholesale like so.

### CODE REVIEW

**Comment by virtuald** [comment]
Crap. All the pack_* that I 'fixed' I set the defaults to False... should be True to stay true to PyGTK.

**Comment by virtuald** [comment]
I'm heading to bed, I think we should merge this once you're done reviewing it and just deal with the pain now instead of putting it off. Part of my rationale is that I'm *sure* at some point they'll get rid of `pygtkcompat`, and I'd rather not deal with that again.

The only reason I can think to not merge this is to make it easier for a dev to figure out what's been looked at and what hasn't. But.. that's what the wiki is for? And then I lost 4 hours of work.

**Comment by virtuald** [comment]
I think I addressed most of your comments, with the exception of the get/set_data stuff. Heading out to work, feel free to address more of them.

**Comment by sjohannes** [comment]
Remaining issues from my review:
* [ ] {get,set}_data - gone
* [ ] osd: pixmap - gone
* [ ] xlgui/preferences/widgets: enable_model_drag_{source,dest} - may need Gtk.TargetEntry.new
* [ ] xlgui/widgets/common: self.window.set_functions(Gdk.FUNC_RESIZE) - gone
* [ ] Search all occurrences of ".popup(" - order of params changed

New issues found from testing:
* [ ] Volume slider covers whole width
* [ ] Menu: stock items and mnemonics don't work
* [ ] Can't open prefs: `'PreferencesDialog' object has no attribute 'set_transient_for'` (xlgui/preferences/\__init__)
* [ ] Non-ASCII chars break in some places - see wiki. The error I've seen is `UnicodeDecodeError: 'ascii' codec can't decode ...`. List below if you find any.
  * [ ] Files panel (xlgui/panel/files)
  * [ ] Track info area (xlgui/widgets/info)
  * [ ] strxfrm used a few times in preferences/{\__init__,plugin} - probably easiest to test with non-latin locale

**Comment by virtuald** [comment]
I've reviewed every python file and none report any lint import errors related to Gtk et al.

**Comment by sjohannes** [comment]
Merged, remaining tasks moved to [main wiki page](https://github.com/exaile/exaile/wiki/PyGI-migration-tasklist-(GTK3-GStreamer-1.x)).

**Comment by genodeftest** [comment]
Did you use a script to do that by the way? Or did you manually change all the references?

**Comment by virtuald** [comment]
There was a script, pygi-convert... I think it's in the pygobject tree somewhere.

**Comment by genodeftest** [comment]
Thanks!

**Pull request merged**
