### PR TITLE
Allowing group tags to be applied to more than one selected song

### PR DESCRIPTION
**Pull request by flberger**
Proposed fix for  #48 "Apply group tag to more that one song at once".

Has been working nicely for me so far.

### CODE REVIEW

**Comment by virtuald** [comment]
Clearly this fell off my radar -- my apologies for that. 

My objection to your patch (I haven't ran it yet) is that you're making changes to the currently selected track(s), which means that the track that is shown in the title isn't actually the one that's being edited.

.. though, it seems like if one did select new track(s), then the title would be updated. Perhaps though you could change the selection mechanism to store tracks in self, instead of self.track, and display to the user [multiple tracks] instead of the single title?

**Comment by flberger** [comment]
Which title display do you mean? On 3.4.3+dc10b58, no title is being displayed upon selection, the status simply reads "Not Playing".
exaile-title-fs8

**Comment by virtuald** [comment]
On the grouptagger panel.

**Comment by virtuald** [comment]
As I said previously, I think the mechanism is a bit confusing and isn't particularly clear on *what* you're actually editing at any given time. I've implemented the functionality as two menu items instead, to 'add tags to all' or 'remove tags from all'. The functionality is available in the GI branch, and will be released with Exaile 4.0.

**Pull request closed without merging**
