### PR TITLE
Add Catalan translation in data/exaile.desktop

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by genodeftest** [comment]
Looks fine. Should go into localization via [weblate](https://hosted.weblate.org/projects/exaile/master/), though.

**Comment by genodeftest** [comment]
To be more specific: We should modify Exaile's builds to localize the ".desktop" file. This is out of scope for such a simple pull request, though.

**Comment by sjohannes** [comment]
Thanks for the patch!

**Comment by sjohannes** [comment]
Wait, I didn't actually merge it in....

**Comment by sjohannes** [comment]
> To be more specific: We should modify Exaile's builds to localize the ".desktop" file.

[For reference.](https://blog.du-a.org/2014/03/17/gettext-desktop/) Not sure if we're supposed to use the same .pot/.po files; might need a separate set so the strings don't end up in the .mo files.

**Pull request merged**
