### PR TITLE
Window title does not change after resuming from pause #779

### PR DESCRIPTION
**Pull request by luzip665**
see #779

### CODE REVIEW

**Comment by luzip665** [comment]
As far as I can see, `on_playback_start` is never called after resume from pause, so it is not necessary to check resume.

**Comment by sjohannes** [comment]
With this, can the `resuming` variable be removed?

Similar code is also present in the previewdevice plugin. Should this be done there as well?

**Comment by luzip665** [comment]
I removed resume in main and previewdevice
Also I added lines to set icon size on playpause and stop initially to prevent later moving (may affect #571)

**Comment by virtuald** [comment]
Works for me. Looks like all of that resuming stuff is pretty old, so probably just vestigial. Thanks!

**Pull request merged**
