### PR TITLE
Show GTK+ theme name in About dialog

### PR DESCRIPTION
**Pull request by sjohannes**
For when we get theme-specific bugs.

### CODE REVIEW

**Comment by virtuald** [comment]
Seems like it should be logged when the GTK version is logged also?

**Comment by sjohannes** [comment]
How about this one? We call `version.register` to log and store the initial value, then just before showing the about dialog we update it.

**Comment by virtuald** [comment]
I don't really see why you'd need to cache it. What if the theme changes at runtime?

**Comment by virtuald** [comment]
Oh I'm an idiot, I misread it earlier.

**Pull request merged**
