### PR TITLE
typo ellipsis, added

### PR DESCRIPTION
**Pull request by leela52452**
[source](https://hosted.weblate.org/projects/exaile/master/source/review/?type=check%3Aellipsis)

### CODE REVIEW

**Comment by genodeftest** [comment]
The travis build fails because the code formatter would change the code you want to push. Can you please run `make format` on your code and update this pull request with these changes?

**Comment by leela52452** [comment]
unfortunately i did not have access to desktop/laptop right now.
i might update later.

**Comment by virtuald** [comment]
Is there a particular reason why we would want to use the ellipsis character instead of three dots? Seems about the same to me. Closing, but if there's a reason to keep this I'm happy to reopen.

**Comment by genodeftest** [comment]
Probably just typographic perfection ;-)

**Pull request closed without merging**
