### PR TITLE
Exclude WASAPI plugin from installer

### PR DESCRIPTION
**Pull request by sjohannes**
Haven't tested this (I don't have the setup to build the installer), hopefully it's correct.

Fixes https://github.com/exaile/exaile/issues/532

Fixes https://github.com/exaile/exaile/issues/534

Fixes https://github.com/exaile/exaile/issues/538

### CODE REVIEW

**Comment by virtuald** [comment]
I've been super busy this month -- will take a look at this and push a (final) rc this weekend?

**Comment by virtuald** [comment]
Works as advertised.

**Comment by sjohannes** [comment]
For future debugging reference: without the wasapi plugin, autoaudiosink now uses waveformsink (not directsoundsink!).

**Comment by virtuald** [comment]
Maybe there's an environment variable we can set to tell the autoaudiosink to use a specific underlying sink?

**Pull request merged**
